"""SQLAlchemy models and database bootstrap for SOC Platform.

The platform runtime database is PostgreSQL only. Legacy SQLite backup
files are no longer used as a fallback at runtime.
"""

from datetime import datetime
import os

from sqlalchemy import Column, DateTime, Float, Integer, String, Text, create_engine
from sqlalchemy.orm import declarative_base, sessionmaker


def get_default_postgres_url() -> str:
    if os.path.exists("/app"):
        return "postgresql+psycopg://soc_platform@postgres:5432/soc_platform"
    return "postgresql+psycopg://soc_platform@localhost:5433/soc_platform"


DATABASE_URL = os.environ.get("DATABASE_URL", get_default_postgres_url())


def create_database_engine(database_url: str):
    """Create a SQLAlchemy engine for the configured runtime database.

    The supported runtime backend is PostgreSQL. Other drivers are not
    configured or tested here.
    """
    return create_engine(database_url)


engine = create_database_engine(DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

Base = declarative_base()

class TriageResult(Base):
    """Triage results from Splunk ES backup toolkit."""
    __tablename__ = "triage_results"
    
    case_id = Column(String, primary_key=True, index=True)
    rule_name = Column(String, index=True)
    rule_id = Column(String, index=True, nullable=True)  # FK to ESCorrelationRule
    verdict = Column(String)  # e.g., "benign", "suspicious", "malicious"
    confidence_score = Column(Float)  # 0.0 to 1.0
    analysis_summary = Column(Text)
    remediation_steps = Column(Text)
    triaged_at = Column(DateTime, default=datetime.utcnow, index=True)

class SplunkEvent(Base):
    """Ingested Splunk events for local analysis."""
    __tablename__ = "splunk_events"
    
    id = Column(Integer, primary_key=True, index=True)
    sourcetype = Column(String, index=True)
    source = Column(String)
    host = Column(String, index=True)
    raw = Column(Text)  # Raw event data
    timestamp = Column(DateTime, index=True)
    ingested_at = Column(DateTime, default=datetime.utcnow)
    
class AnalysisResult(Base):
    """AI-generated analysis results using Ollama."""
    __tablename__ = "analysis_results"
    
    id = Column(Integer, primary_key=True, index=True)
    case_id = Column(String, index=True)
    model_name = Column(String)  # e.g., "llama2", "mistral"
    query = Column(Text)  # The prompt sent to Ollama
    analysis = Column(Text)  # The LLM response
    confidence = Column(Float)  # Model's confidence
    created_at = Column(DateTime, default=datetime.utcnow, index=True)

class ESCorrelationRule(Base):
    """Splunk Enterprise Security correlation rules."""
    __tablename__ = "es_correlation_rules"
    
    id = Column(Integer, primary_key=True, index=True)
    rule_id = Column(String, unique=True, index=True)
    rule_name = Column(String, index=True)
    description = Column(Text)
    category = Column(String, index=True)
    severity = Column(String)
    drilldown_fields = Column(Text)  # JSON array
    required_closure_fields = Column(Text)  # JSON array
    closure_template = Column(Text)
    enabled = Column(Integer, default=1)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ClosureNote(Base):
    """Generated closure notes for incidents."""
    __tablename__ = "closure_notes"
    
    id = Column(Integer, primary_key=True, index=True)
    case_id = Column(String, index=True)
    rule_id = Column(String, index=True)
    analyst_notes = Column(Text)
    generated_note = Column(Text)
    status = Column(String, default="draft")  # draft, submitted, closed
    created_at = Column(DateTime, default=datetime.utcnow)
    submitted_at = Column(DateTime)

class SupportiveQuery(Base):
    """Supportive SPL queries tied to specific correlation rules."""
    __tablename__ = "supportive_queries"

    id = Column(Integer, primary_key=True, index=True)
    rule_id = Column(String, index=True)
    title = Column(String, index=True)
    description = Column(Text)
    spl_query = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)


class SupportiveQueryResult(Base):
    """Stored results from running supportive queries for a specific case.

    This lets the SOC app and local models consume enrichment/evidence
    generated by running supportive SPL/SQL outside the platform.
    """

    __tablename__ = "supportive_query_results"

    id = Column(Integer, primary_key=True, index=True)
    case_id = Column(String, index=True)
    rule_id = Column(String, index=True)
    query_title = Column(String, index=True)
    source_system = Column(String, default="splunk")  # e.g., splunk, sql, other
    raw_result = Column(Text)  # JSON or text blob of the query output
    created_at = Column(DateTime, default=datetime.utcnow, index=True)


class InvestigationState(Base):
    """Persistent investigation loop state for a triage case.

    This tracks the current working hypothesis, evidence balance, open
    questions, closure blockers, and next best actions across repeated
    analysis/evidence-save cycles.
    """

    __tablename__ = "investigation_states"

    case_id = Column(String, primary_key=True, index=True)
    rule_id = Column(String, index=True)
    current_hypothesis = Column(Text)
    provisional_disposition = Column(String, index=True)
    disposition_confidence = Column(Float)
    loop_status = Column(String, index=True)
    iteration_count = Column(Integer, default=0)
    unresolved_questions = Column(Text)  # JSON array
    closure_blockers = Column(Text)  # JSON array
    recommended_next_actions = Column(Text)  # JSON array
    evidence_summary = Column(Text)  # JSON object
    last_analysis_stage = Column(String, default="initial")
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, index=True)


class PlaceholderAlias(Base):
    """Dynamic placeholder aliases for supportive SPL templates.

    Each alias maps a short logical name (e.g., "host", "dest", "user")
    to a list of candidate notable fields that can supply values when
    rendering supportive queries with $placeholder$ tokens.

    The `fields` column is stored as a JSON-encoded list of strings to keep
    the schema simple and portable across relational database backends.
    """

    __tablename__ = "placeholder_aliases"

    id = Column(Integer, primary_key=True, index=True)
    alias = Column(String, unique=True, index=True)
    fields = Column(Text)  # JSON-encoded ["field1", "field2", ...]
    description = Column(Text)


class CodeReview(Base):
    """Code review results from Ollama LLM analysis."""
    __tablename__ = "code_reviews"

    id = Column(Integer, primary_key=True, index=True)
    code_snippet = Column(Text)
    language = Column(String, default="python")
    review_result = Column(Text)
    model_name = Column(String, default="llama3.1:latest")
    created_at = Column(DateTime, default=datetime.utcnow, index=True)


class ToolRun(Base):
    """Persistent execution record shared by every catalog tool."""

    __tablename__ = "tool_runs"

    job_id = Column(String, primary_key=True, index=True)
    tool_name = Column(String, index=True)
    arguments = Column(Text)  # JSON object
    status = Column(String, index=True, default="pending")
    stdout = Column(Text)
    stderr = Column(Text)
    exit_code = Column(Integer)
    artifact_paths = Column(Text)  # JSON array of repo-relative paths
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    completed_at = Column(DateTime)

# Create tables
Base.metadata.create_all(bind=engine)

def get_db():
    """Dependency for FastAPI to get DB session."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
