"""SQLAlchemy models and database bootstrap for SOC Platform."""

from datetime import datetime
import os

from sqlalchemy import Column, DateTime, Float, Integer, String, Text, create_engine
from sqlalchemy.orm import declarative_base, sessionmaker


def get_default_sqlite_url() -> str:
    platform_root = os.environ.get("SOC_PLATFORM_ROOT")
    if platform_root:
        db_path = os.path.join(platform_root, "splunk-es-backup-toolkit", "triage.db")
    else:
        repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
        db_path = os.path.join(repo_root, "splunk-es-backup-toolkit", "triage.db")
    normalized = db_path.replace("\\", "/")
    return f"sqlite:///{normalized}"


def get_default_postgres_url() -> str:
    if os.path.exists("/app"):
        return "postgresql+psycopg://soc_platform@postgres:5432/soc_platform"
    return "postgresql+psycopg://soc_platform@localhost:5433/soc_platform"


DATABASE_URL = os.environ.get("DATABASE_URL", get_default_postgres_url())


def create_database_engine(database_url: str):
    engine_kwargs = {}
    if database_url.startswith("sqlite"):
        engine_kwargs["connect_args"] = {"check_same_thread": False}
    return create_engine(database_url, **engine_kwargs)


engine = create_database_engine(DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

Base = declarative_base()

class TriageResult(Base):
    """Triage results from Splunk ES backup toolkit."""
    __tablename__ = "triage_results"
    
    case_id = Column(String, primary_key=True, index=True)
    rule_name = Column(String, index=True)
    rule_id = Column(String, index=True, nullable=True)  # FK to ESCorrelationRule
    verdict = Column(String)  # e.g., "benign", "suspicious", "malicious"
    confidence_score = Column(Float)  # 0.0 to 1.0
    analysis_summary = Column(Text)
    remediation_steps = Column(Text)
    triaged_at = Column(DateTime, default=datetime.utcnow, index=True)

class SplunkEvent(Base):
    """Ingested Splunk events for local analysis."""
    __tablename__ = "splunk_events"
    
    id = Column(Integer, primary_key=True, index=True)
    sourcetype = Column(String, index=True)
    source = Column(String)
    host = Column(String, index=True)
    raw = Column(Text)  # Raw event data
    timestamp = Column(DateTime, index=True)
    ingested_at = Column(DateTime, default=datetime.utcnow)
    
class AnalysisResult(Base):
    """AI-generated analysis results using Ollama."""
    __tablename__ = "analysis_results"
    
    id = Column(Integer, primary_key=True, index=True)
    case_id = Column(String, index=True)
    model_name = Column(String)  # e.g., "llama2", "mistral"
    query = Column(Text)  # The prompt sent to Ollama
    analysis = Column(Text)  # The LLM response
    confidence = Column(Float)  # Model's confidence
    created_at = Column(DateTime, default=datetime.utcnow, index=True)

class ESCorrelationRule(Base):
    """Splunk Enterprise Security correlation rules."""
    __tablename__ = "es_correlation_rules"
    
    id = Column(Integer, primary_key=True, index=True)
    rule_id = Column(String, unique=True, index=True)
    rule_name = Column(String, index=True)
    description = Column(Text)
    category = Column(String, index=True)
    severity = Column(String)
    drilldown_fields = Column(Text)  # JSON array
    required_closure_fields = Column(Text)  # JSON array
    closure_template = Column(Text)
    enabled = Column(Integer, default=1)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ClosureNote(Base):
    """Generated closure notes for incidents."""
    __tablename__ = "closure_notes"
    
    id = Column(Integer, primary_key=True, index=True)
    case_id = Column(String, index=True)
    rule_id = Column(String, index=True)
    analyst_notes = Column(Text)
    generated_note = Column(Text)
    status = Column(String, default="draft")  # draft, submitted, closed
    created_at = Column(DateTime, default=datetime.utcnow)
    submitted_at = Column(DateTime)

class SupportiveQuery(Base):
    """Supportive SPL queries tied to specific correlation rules."""
    __tablename__ = "supportive_queries"

    id = Column(Integer, primary_key=True, index=True)
    rule_id = Column(String, index=True)
    title = Column(String, index=True)
    description = Column(Text)
    spl_query = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)


class SupportiveQueryResult(Base):
    """Stored results from running supportive queries for a specific case.

    This lets the SOC app and local models consume enrichment/evidence
    generated by running supportive SPL/SQL outside the platform.
    """

    __tablename__ = "supportive_query_results"

    id = Column(Integer, primary_key=True, index=True)
    case_id = Column(String, index=True)
    rule_id = Column(String, index=True)
    query_title = Column(String, index=True)
    source_system = Column(String, default="splunk")  # e.g., splunk, sql, other
    raw_result = Column(Text)  # JSON or text blob of the query output
    created_at = Column(DateTime, default=datetime.utcnow, index=True)

# Create tables
Base.metadata.create_all(bind=engine)

def get_db():
    """Dependency for FastAPI to get DB session."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
