#!/usr/bin/env python3
"""Hash-pin requirements.txt and requirements-dev.txt: full closure, both branches.

Why this exists: pip turns on --require-hashes AUTOMATICALLY the moment any
requirement in a file carries a --hash (pip 26 says so itself: "it turns on
automatically when any package has a hash"). Partial pinning is therefore
impossible — one hashed line means every requirement pip may resolve from
those files must be hashed too, transitives included, for BOTH marker
branches (3.14 production, 3.9 CI) or the CI install step dies mid-resolver.

How it works:
  1. Resolve each requirements file twice with pip's own resolver
     (pip install --dry-run --ignore-installed --report): under .venv314 for
     the python_version >= "3.10" branch, and under a throwaway 3.9 tool venv
     for the < "3.10" branch (the legacy .venv ships pip 21, which predates
     --report; it is only used as the interpreter source for the tool venv).
  2. For every resolved (name, version), fetch ALL sha256 digests PyPI
     publishes (sdist + every platform wheel) so any CI/local platform
     installs without a hash miss.
  3. Guardrail: a dependency gated by a sys_platform/platform_* marker may be
     invisible from this Mac (witnessed: sqlalchemy==2.0.52 needs greenlet on
     linux/x86_64 but not on Apple Silicon) — any marker that selects a dep on
     CPython linux/x86_64 (the CI runner) but not here, with that dep absent
     from the resolution, is resolved by a nested pip run and folded into the
     lock. Loud failure if that cannot converge.
  4. Rewrite each file: existing comments and blank lines preserved, inline
     trailing comments moved above their pin (an inline comment would swallow
     the line-continuation backslash), every pin emitted pip-compile style
     (`name==ver ; marker \\` + indented `--hash=sha256:` lines), and a
     transitive section appended covering everything the pins above do not
     declare. Same version on both branches -> one unmarked line; different
     versions -> one line per branch with its marker. Idempotent: re-running
     re-derives the hashes from fresh resolutions.

Stdlib + `packaging` (present in every venv that has the test deps; a
sys.path fallback into .venv314/.venv covers a bare system python3). Needs
network (pip resolver + PyPI). Overrides: PIN_PY314, PIN_PY39.
Exit 0 = files rewritten and coverage-checked; anything else = loud failure.
"""

import glob
import json
import os
import re
import shutil
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

try:
    from packaging.markers import Marker, default_environment
    from packaging.requirements import Requirement
except ImportError:  # bare system python: borrow packaging from the project venvs
    for pat in (".venv314/lib/python*/site-packages", ".venv/lib/python*/site-packages"):
        hits = sorted(glob.glob(str(Path(__file__).resolve().parent.parent / pat)))
        if hits:
            sys.path.append(hits[-1])
    from packaging.markers import Marker, default_environment
    from packaging.requirements import Requirement

ROOT = Path(__file__).resolve().parent.parent
FILES = ["requirements.txt", "requirements-dev.txt"]
TRANSMARK = "# --- transitive pins (generated by scripts/pin_requirements.py"
UA = "soc-plaform-pin-requirements/1.0"
PLATFORM_VARS = (
    "sys_platform", "platform_system", "platform_machine", "os_name",
    "platform_python_implementation", "implementation_name",
)
HASH_LINE_RE = re.compile(r"^\s*--hash=sha256:[0-9a-fA-F]+\s*\\?$")
PIN_EXPR_RE = re.compile(
    r"^(?P<name>[A-Za-z0-9][A-Za-z0-9._-]*)(?:\[(?P<extras>[^\]]+)\])?"
    r"==(?P<version>[^\s;]+)(?:;\s*(?P<marker>.+))?$"
)


def canon(name):
    return re.sub(r"[-_.]+", "-", name).lower()


def die(msg):
    print("FAIL: %s" % msg, file=sys.stderr)
    sys.exit(1)


def run(cmd, **kw):
    proc = subprocess.run(cmd, capture_output=True, text=True, **kw)
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr[-4000:])
        die("command failed: %s" % " ".join(str(c) for c in cmd))
    return proc


def py314():
    path = os.environ.get("PIN_PY314", str(ROOT / ".venv314/bin/python"))
    if not os.access(path, os.X_OK):
        die("Python 3.14 venv not found at %s (set PIN_PY314)" % path)
    return path


def py39():
    path = os.environ.get("PIN_PY39")
    if path:
        if not os.access(path, os.X_OK):
            die("PIN_PY39=%s is not executable" % path)
        return path
    tool = Path(os.environ.get("TMPDIR", "/tmp")) / "soc-pin39/bin/python"
    if not os.access(tool, os.X_OK):
        base = ROOT / ".venv/bin/python"
        if not os.access(base, os.X_OK):
            base = shutil.which("python3.9")
        if not base:
            die("no Python 3.9 interpreter found (.venv or PATH) — set PIN_PY39")
        run([base, "-m", "venv", str(tool.parent.parent)])
        run([str(tool), "-m", "pip", "install", "-q", "--upgrade", "pip"])
    return str(tool)


def resolve(py, req_arg):
    """pip's own resolution of one requirements file (or single requirement)."""
    out = Path(os.environ.get("TMPDIR", "/tmp")) / (
        "pin-report-%d-%d.json" % (os.getpid(), time.time_ns())
    )
    run([py, "-m", "pip", "install", "--dry-run", "--ignore-installed",
         "--quiet", "--report", str(out), *req_arg])
    try:
        report = json.loads(out.read_text())
    finally:
        out.unlink(missing_ok=True)
    resolved = {}
    for item in report.get("install", []):
        meta = item["metadata"]
        resolved[canon(meta["name"])] = {
            "name": meta["name"],
            "version": meta["version"],
            "requires": meta.get("requires_dist") or [],
            "yanked": item.get("is_yanked", False),
        }
    if not resolved:
        die("resolver produced an empty install set for: %s" % " ".join(req_arg))
    return resolved


def pypi_hashes(name, version):
    """Every sha256 PyPI publishes for a version (sdist + all platform wheels)."""
    key = "%s/%s" % (name, version)
    url = "https://pypi.org/pypi/%s/json" % key
    last = None
    for attempt in range(3):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": UA})
            with urllib.request.urlopen(req, timeout=20) as resp:
                payload = json.load(resp)
            hashes = sorted({
                f["digests"]["sha256"]
                for f in payload.get("urls", [])
                if f.get("digests", {}).get("sha256")
            })
            if not hashes:
                die("PyPI reports no sha256 for %s" % key)
            return hashes
        except urllib.error.HTTPError as exc:
            if exc.code == 404 and name != name.replace("-", "_"):
                name = name.replace("-", "_")  # legacy PyPI URL spelling
                url = "https://pypi.org/pypi/%s/json" % ("%s/%s" % (name, version))
                continue
            last = "HTTP %d" % exc.code
        except (urllib.error.URLError, OSError, ValueError) as exc:
            last = str(exc)
        if attempt < 2:
            time.sleep(1)
    die("could not fetch hashes for %s (%s)" % (key, last))


def env_for(python_version, linux):
    env = dict(default_environment())
    env.update(extra="", python_version=python_version,
               python_full_version=python_version + ".0")
    if linux:
        env.update(sys_platform="linux", platform_system="Linux",
                   platform_machine="x86_64", os_name="posix",
                   implementation_name="cpython",
                   platform_python_implementation="CPython")
    return env


def find_linux_only(resolved, python_version):
    """Deps a linux/x86_64 CI runner would pull that this Mac does not."""
    missing = []
    linux, darwin = env_for(python_version, True), env_for(python_version, False)
    for pkg in resolved.values():
        for raw in pkg["requires"]:
            try:
                req = Requirement(raw)
            except Exception:
                continue
            if not req.marker or not any(v in str(req.marker) for v in PLATFORM_VARS):
                continue
            if (req.marker.evaluate(linux) and not req.marker.evaluate(darwin)
                    and canon(req.name) not in resolved):
                missing.append(req)
    return missing


def expand_linux_only(py, resolved, python_version):
    """Fold linux-only deps into the lock (bounded fixpoint)."""
    for _ in range(3):
        missing = find_linux_only(resolved, python_version)
        if not missing:
            return
        for req in missing:
            spec = str(req.specifier) if req.specifier else ""
            if not spec:
                die("linux-only dependency %s has no version specifier — "
                    "pin it manually before hashing" % req.name)
            print("     + linux-only dep: %s%s (invisible from this Mac)"
                  % (req.name, spec))
            nested = resolve(py, ["%s%s" % (req.name, spec)])
            for key, val in nested.items():
                resolved.setdefault(key, val)
    die("linux-only dependency expansion did not converge")


def marker_selects_branch(marker, branch):
    if not marker:
        return True
    env = dict(default_environment())
    env.update(extra="", python_version=branch, python_full_version=branch + ".0")
    return Marker(marker).evaluate(env)


def get_hashes(hash_map, name, version, context):
    try:
        return hash_map[(name, version)]
    except KeyError:
        die("%s: no hashes collected for %s==%s — the resolver did not "
            "select that pin on either branch" % (context, name, version))


def parse_file(path):
    """-> (original lines, pin records before the transitive block, direct names)."""
    pins, direct = [], set()
    lines = path.read_text().splitlines()
    for lineno, raw in enumerate(lines, 1):
        stripped = raw.strip()
        if stripped.startswith(TRANSMARK):
            break
        if not stripped or stripped.startswith("#") or HASH_LINE_RE.match(raw):
            continue
        base, sep, comment = stripped.partition("#")
        base = base.rstrip("\\").strip()
        match = PIN_EXPR_RE.match(base)
        if not match:
            die("%s:%d: unsupported line %r — only `name==version[; marker]` "
                "pins are handled" % (path.name, lineno, raw))
        pins.append({
            "base": base,
            "comment": comment.strip() if sep else None,
            "name": canon(match.group("name")),
            "version": match.group("version"),
            "marker": (match.group("marker") or "").strip() or None,
        })
        direct.add(canon(match.group("name")))
    return lines, pins, direct


def emit_pin(out, base, hashes):
    out.append(base + " \\")
    for digest in hashes[:-1]:
        out.append("    --hash=sha256:%s \\" % digest)
    out.append("    --hash=sha256:%s" % hashes[-1])


def main():
    os.chdir(ROOT)
    py14, py09 = py314(), py39()
    print("branches: 3.14 <- %s | 3.9 <- %s" % (py14, py09))

    for filename in FILES:
        path = ROOT / filename
        print("── %s ──" % filename)
        lines, pins, direct = parse_file(path)

        r14 = resolve(py14, ["-r", str(path)])
        r09 = resolve(py09, ["-r", str(path)])
        print("     resolved: %d pkgs (3.14 branch), %d pkgs (3.9 branch)"
              % (len(r14), len(r09)))
        expand_linux_only(py14, r14, "3.14")
        expand_linux_only(py09, r09, "3.9")

        # union of (name, version) needing hashes
        versions = {}
        for branch in (r14, r09):
            for key, val in branch.items():
                versions.setdefault(key, set()).add(val["version"])
        hash_map = {}
        for key, vers in sorted(versions.items()):
            for version in sorted(vers):
                hash_map[(key, version)] = pypi_hashes(key, version)
            for version in sorted(vers):
                for branch_name, branch in (("3.14", r14), ("3.9", r09)):
                    pkg = branch.get(key)
                    if pkg and pkg["version"] == version and pkg["yanked"]:
                        print("     WARNING: %s==%s is yanked on PyPI"
                              % (key, version))

        # transitive synthesis (everything the pins above do not declare)
        transitive = sorted((set(r14) | set(r09)) - direct)
        trans_lines, coverage = [], {"3.14": set(), "3.9": set()}
        for key in transitive:
            v14 = r14.get(key, {}).get("version")
            v09 = r09.get(key, {}).get("version")
            name = (r14.get(key) or r09[key])["name"]
            if v14 and v09 and v14 == v09:
                emit_pin(trans_lines, "%s==%s" % (name, v14),
                         hash_map[(key, v14)])
                coverage["3.14"].add(key)
                coverage["3.9"].add(key)
            elif v14 and v09:
                # different version per branch: one marker-selected line each
                emit_pin(trans_lines, "%s==%s; python_version >= \"3.10\""
                         % (name, v14), hash_map[(key, v14)])
                emit_pin(trans_lines, "%s==%s; python_version < \"3.10\""
                         % (name, v09), hash_map[(key, v09)])
                coverage["3.14"].add(key)
                coverage["3.9"].add(key)
            elif v14:
                emit_pin(trans_lines, "%s==%s; python_version >= \"3.10\""
                         % (name, v14), hash_map[(key, v14)])
                coverage["3.14"].add(key)
            else:
                emit_pin(trans_lines, "%s==%s; python_version < \"3.10\""
                         % (name, v09), hash_map[(key, v09)])
                coverage["3.9"].add(key)

        # coverage: every resolved pkg must have a branch-active pin line
        for branch_name, resolved in (("3.14", r14), ("3.9", r09)):
            active_directs = {
                p["name"] for p in pins
                if marker_selects_branch(p["marker"], branch_name)
            }
            for key in resolved:
                if key in direct:
                    if key not in active_directs:
                        die("%s: %s is pinned only under a marker that does "
                            "not select Python %s — add the other branch's pin"
                            % (filename, key, branch_name))
                elif key not in coverage[branch_name]:
                    die("%s: %s (Python %s) fell through pin/coverage "
                        "synthesis — file a bug" % (filename, key, branch_name))

        # rewrite: preserve comments/blanks, drop old hashes + old block
        out = []
        for raw in lines:
            stripped = raw.strip()
            if stripped.startswith(TRANSMARK):
                break
            if HASH_LINE_RE.match(raw):
                continue
            if not stripped or stripped.startswith("#"):
                out.append(raw)
                continue
            base, sep, comment = stripped.partition("#")
            base = base.rstrip("\\").strip()
            match = PIN_EXPR_RE.match(base)
            if not match:
                die("%s: unparsable line during rewrite: %r" % (filename, raw))
            if sep and comment.strip():
                out.append("# " + comment.strip())
            emit_pin(out, base, get_hashes(
                hash_map, canon(match.group("name")), match.group("version"),
                filename))
        # exactly one blank line before the block, however many runs preceded
        while out and not out[-1].strip():
            out.pop()
        out.append("")
        out.append(TRANSMARK + " ---")
        out.append("# Full closure of the pins above, hash-locked for both marker")
        out.append("# branches (sdist + every platform wheel). Regenerate with:")
        out.append("#     scripts/pin_requirements.py")
        out.extend(trans_lines)

        path.write_text("\n".join(out) + "\n")
        total_hashes = sum(len(v) for v in hash_map.values())
        print("     wrote %s: %d pins hashed, %d transitive pins, %d digests"
              % (filename, len(pins), len(transitive), total_hashes))

    print("OK: requirements files hash-locked (full closure, both branches)")


if __name__ == "__main__":
    sys.exit(main())
